[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/api/summarize"
  to = "/.netlify/functions/summarize"
  status = 200
  force = true

[functions]
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"