[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  external_node_modules = ["@netlify/functions"]
  node_bundler = "esbuild"